First version of API without Unit tests
Lugdunum3D/LugBench-API pull request #1
Opened 2017-05-04 19:24 UTC by mapy69003

2017-05-04 19:29 UTC, yoannpicquenot reviewed
- Console.log('') to remove
- Four spaces of indentation

2017-05-04 19:29 UTC, mapy69003 commented on v1/index.js
> +    console.log(err);
Not very useful

2017-05-04 19:29 UTC, mapy69003 commented on v1/index.js
> +'use strict';
Four spaces of indentation

2017-05-04 19:29 UTC, mapy69003 commented on server.js
> +'use strict';
Four spaces of indentation

2017-05-04 19:29 UTC, mapy69003 commented on package.json
> +{
Missing engines field.

2017-05-04 19:29 UTC, mapy69003 commented on index.js
> +var express = require('express');
Four spaces of indentation

2017-05-04 19:29 UTC, mapy69003 commented on config/index.js
> +module.exports = {
Four spaces of indentation

2017-05-04 19:29 UTC, mapy69003 commented on v1/models/gpu/index.js
> +var mongoose = require('mongoose');
Four spaces of indenation

2017-05-04 19:44 UTC, saveman71 commented
Waiting for #2

2017-05-04 20:01 UTC, saveman71 requested changes

2017-05-04 20:01 UTC, saveman71 commented on v1/index.js
> +        res.send({
Why is this different than 10 lines above?

2017-05-04 20:01 UTC, saveman71 commented on server.js
> +    console.log(err || ("Successfully connected to the db"));
Un-necessary parens

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/formats.js
> +        let _val = val;
Why?

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/uint10.js
> +        let _val = Number(val);
Why?

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/formats.js
> +module.exports = function (mongoose) {
Space after `function`

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/formats.js
> +    Formats.prototype.cast = function (val) {
Space after `function`

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/uint10.js
> +module.exports = function (mongoose) {
Space after `function`

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/uint10.js
> +    Uint10.prototype.cast = function (val) {
Space after `function`

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/uint12.js
> +module.exports = function (mongoose) {
Space after `function`

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/uint12.js
> +    Uint12.prototype.cast = function (val) {
Space after `function`

2017-05-04 20:01 UTC, saveman71 commented on server.js
> +    server.use(function(req, res, next) {
Arrow function

2017-05-04 20:01 UTC, saveman71 commented on index.js
> +            res.sendFile(__dirname + '/notfound.html');
Status is not 404

2017-05-04 20:01 UTC, saveman71 commented on package.json
> +  "license": "ISC",
MIT

2017-05-04 20:01 UTC, saveman71 commented on package.json
> +  "license": "ISC",
+ add https://github.com/Lugdunum3D/glTF2-loader/blob/master/LICENSE at the root, replacing glTF2-loader with LugBench-API

2017-05-04 20:01 UTC, saveman71 commented on server.js
> +var api = require('./index.js');
`./index`

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/uint10.js
> +module.exports = function (mongoose) {
Add `'use strict';`

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/uint12.js
> +module.exports = function (mongoose) {
Add `'use strict';`

2017-05-04 20:01 UTC, saveman71 commented on v1/models/gpu/index.js
> +var mongoose = require('mongoose');
Add `'use strict';`

2017-05-04 20:01 UTC, saveman71 commented on v1/customTypes/formats.js
> +module.exports = function (mongoose) {
Add `'use strict';`

2017-05-04 20:01 UTC, saveman71 commented on v1/index.js
> +var mongoose = require('mongoose');
Move mongoose before router

2017-05-04 20:01 UTC, saveman71 commented on v1/models/gpu/index.js
> +module.exports = function() {
`module.exports = mongoose.model('Gpu', gpuSchema);` instead.

2017-05-04 20:01 UTC, saveman71 commented on v1/models/gpu/index.js
> +    return mongoose.model('gpu', schema);
`gpu` => `Gpu`, as schema should begin with an uppercase letter, do not change the folder though

2017-05-04 22:41 UTC, mapy69003 commented on v1/customTypes/uint10.js
> +        let _val = Number(val);
http://mongoosejs.com/docs/customschematypes.html

2017-05-04 22:41 UTC, mapy69003 commented on v1/customTypes/formats.js
> +        let _val = val;
http://mongoosejs.com/docs/customschematypes.html

2017-05-05 00:34 UTC, cchardeau commented on notfound.html
> +                <h1>This api route doesn't exist</h1></div>
A 404 page with more style?

2017-05-05 01:23 UTC, mapy69003 commented on notfound.html
> +                <h1>This api route doesn't exist</h1></div>
Not really important. I made an update which removes this page.

2017-05-05 14:53 UTC, closed without merging