Added documentation
Lugdunum3D/LugBench-API pull request #6
Opened 2017-05-06 17:13 UTC by mapy69003

2017-05-07 11:16 UTC, Quentin01 requested changes

2017-05-07 11:16 UTC, Quentin01 commented on README.md
> +```shell=
In markdown it's only `shell` and not `shell=`

2017-05-07 11:16 UTC, Quentin01 commented on README.md
> +git clone git@github.com:Lugdunum3D/LugBench-API.git
Use the https link for users, it's better.

2017-05-07 11:16 UTC, Quentin01 commented on README.md
> +```shell=
Same remark `shell`

2017-05-07 11:16 UTC, Quentin01 commented on README.md
> +:::info
What are you doing with `:::info`? Do you mean `##info`?

2017-05-07 11:16 UTC, Quentin01 commented on README.md
> +```shell=
Same remark, `shell`

2017-05-07 11:16 UTC, Quentin01 commented on README.md
> +:::
What are you doing with `:::`?

2017-05-07 11:16 UTC, Quentin01 commented on README.md
> +# Routes
It's great to have all the routes, but can't we provide also the content of the JSON? With a JSON Schema for example.

2017-05-07 15:43 UTC, mapy69003 commented on README.md
> +```shell=
My bad, it's Hackmd autocompletion

2017-05-07 15:44 UTC, mapy69003 commented on README.md
> +:::info
I thought it was right. Because on hackmd it works

2017-05-07 15:45 UTC, mapy69003 commented on README.md
> +# Routes
:+1:

2017-05-07 20:04 UTC, saveman71 requested changes

2017-05-07 20:04 UTC, saveman71 commented on README.md
> +Download the project [here](https://github.com/Lugdunum3D/LugBench-API/archive/dev.zip)
I honestly don't think any of the users might want to do that.

2017-05-07 20:04 UTC, saveman71 commented on README.md
> +**NOTE**: The default port is 5000. If you want to set a different one for the API to listen, set a environment variable system like this:
I think NOTE is better as "Note" as it's done on our docs.

2017-05-08 00:54 UTC, closed without merging

2017-05-08 01:40 UTC, Quentin01 commented on README.md
> +Download the project [here](https://github.com/Lugdunum3D/LugBench-API/archive/dev.zip)
I was talking about cloning by https not downloading the project.
`git clone https://github.com/Lugdunum3D/LugBench-API.git`