Added authentication middleware
Lugdunum3D/LugBench-API pull request #7
Opened 2017-05-06 17:59 UTC by mapy69003

2017-05-07 11:22 UTC, Quentin01 requested changes

2017-05-07 11:22 UTC, Quentin01 commented on middleware/index.js
> +'use strict';
Why are you naming this middleware `index.js`?

2017-05-07 11:22 UTC, Quentin01 commented on middleware/index.js
> +  let accessToken = req.headers['x-access-token'];
Don't we use 4 spaces for indentation everywhere in the project? (We can change that maybe)

2017-05-07 11:22 UTC, Quentin01 commented on middleware/index.js
> +  next();
I think that you don't want to call next in case of error 401

2017-05-07 11:22 UTC, Quentin01 commented on server.js
> +var middleware = require('./middleware');
Change also the name of this variable, it's an authentification middleware

2017-05-07 11:22 UTC, Quentin01 commented on server.js
> +    server.use('/api/', middleware);
Why are you protecting `/api/` with the authentification middleware?

2017-05-07 19:59 UTC, saveman71 requested changes

2017-05-07 19:59 UTC, saveman71 commented on middleware/authentication.js
> +    if (methodToCatch.indexOf(req.method) !== -1) {
This is very very basic but it's a start. What if it's just a GET? No next?

2017-05-07 19:59 UTC, saveman71 commented on server.js
> +var middlewareAuthentication = require('./middleware/authentication.js');
-.js

2017-05-07 19:59 UTC, saveman71 commented on config/index.js
> +    auth_token: process.env.AUTH_TOKEN
Maybe you should add a check earlier in the file to ensure the auth_token is an ok value, or later you'll check against `undefined`

2017-05-08 16:33 UTC, Quentin01 requested changes

2017-05-08 16:33 UTC, Quentin01 commented on middleware/authentication.js
> +    if (methodToCatch.indexOf(req.method) !== -1) {
Why do you want to only catch these methods? We will maybe have some `GET` endpoints that we will protect.

2017-05-08 16:33 UTC, Quentin01 commented on middleware/authentication.js
> +    if (methodToCatch.indexOf(req.method) !== -1) {
You have still failed your conditions, `next()` is not called when the access token is good.

2017-05-08 16:33 UTC, Quentin01 commented on server.js
> +    server.use('/api/', middlewareAuthentication);
Why are you protecting all the endpoints? We just want to protect the sensitive endpoints (admin ones)

2017-05-15 16:11 UTC, mapy69003 commented
@Quentin01 can you check please?

2017-05-23 11:39 UTC, Quentin01 approved these changes

2017-05-23 11:40 UTC, Quentin01 commented
@saveman71 Do you also approve the final changes?

2017-05-23 13:53 UTC, saveman71 approved these changes

2017-05-23 13:54 UTC, merged