Update readme
Lugdunum3D/LugBench-API pull request #9
Opened 2017-05-08 00:55 UTC by mapy69003

2017-05-08 16:37 UTC, Quentin01 requested changes

2017-05-08 16:37 UTC, Quentin01 commented on README.md
> +#### Details for a Gpu can be found [here](./v1/models/gpu/GPU.md)
Why are you using `####`? It's for title, not to highlight something

2017-05-08 16:37 UTC, Quentin01 commented on README.md
> +#### Details for a Gpu can be found [here](./v1/models/gpu/GPU.md)
And do you really want to just copy/paste the schema of the model? The user still doesn't know what is the exact JSON for each routes.

2017-05-15 16:17 UTC, mapy69003 commented on README.md
> +#### Details for a Gpu can be found [here](./v1/models/gpu/GPU.md)
There's only one JSON model for each route.

2017-05-15 16:19 UTC, mapy69003 commented on README.md
> +#### Details for a Gpu can be found [here](./v1/models/gpu/GPU.md)
I don't have a better solution

2017-05-23 11:37 UTC, Quentin01 requested changes

2017-05-23 11:37 UTC, Quentin01 commented on README.md
> +Details for a Gpu can be found [here](./v1/models/gpu/GPU.md)
Because the markdown file is just a copy/paste from the Mongoose schema, maybe you can just add a link to the JS file instead?

2017-05-29 12:04 UTC, mapy69003 commented
@Quentin01 is it mergeable?

2017-05-29 12:05 UTC, Quentin01 approved these changes

2017-05-29 12:05 UTC, merged